### PR TITLE
Removing bespoke credentials in favour of default chain

### PR DESCRIPTION
**Pull request by davidporter-id-au**
Changes the provider to use the standard AWS creds lookup

Looks up Envars first, followed by ec2 metadata endpoint, followed by profile (or [something to that effect[](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html)).  This allows this plugin to work in environments such as Amazon codebuild, where the credentials are provided only by ec2 metadata, and not profile.

### CODE REVIEW

**Comment by nf-versent** [comment]
@gkatzioura Would really appreciate if you could take a look at this PR please? If it's ok, would you mind creating another release?

**Comment by gkatzioura** [comment]
Thank for the effort. Really appreciate that. I think the change should be on the 
CredentialsFactory

```java
public class CredentialsFactory {

    public AWSStaticCredentialsProvider create(AuthenticationInfo authenticationInfo) {

        final AWSCredentials awsCredentials;

        if(authenticationInfo==null) {
            awsCredentials = DefaultAWSCredentialsProviderChain();
        } else {
            awsCredentials = new BasicAWSCredentials(authenticationInfo.getUserName(),authenticationInfo.getPassword());
        }

        return new AWSStaticCredentialsProvider(awsCredentials);
    }
```

People might still want to add the credentials the maven way.
What do you think?

**Comment by davidporter-id-au** [comment]
Up to you, that should work, but imho I don't see it as being necessary unless you're authenticating in a manner I'm not familiar with - the [default credential chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) does a fallback to basic credentials or profile if you prefer?

**Comment by gkatzioura** [comment]
Yeap It's the usual maven settings.xml way to add a repo.
So I will proceed with the approach mentioned, make the changes to the branch and then check if it works on an ec2 machine with a role that accesses the bucket.

**Comment by davidporter-id-au** [comment]
Awesome! thank you for this.

**Comment by gkatzioura** [comment]
Hi there is a new version 1.2 that has the change in order to satisfy this requirement.
I close this ticket without merging since the change was a bit different.
Tested it with aws roles

**Pull request closed without merging**
