### PR TITLE
Issue 1 and 2

### PR DESCRIPTION
**Pull request by mstump**
Closes issues #1 and #2 

* Shade and relocate google dependencies to work around gradle included libraries. 
* List GCS bucket instead of buckets so we don't need elevated permissions.

### CODE REVIEW

**Comment by ankushg** [comment]
@gkatzioura any chance this can get merged?

**Comment by bhtucker** [comment]
@gkatzioura This correction to the 'list buckets' check would make this much more usable

**Comment by ruschecker** [comment]
It looks like author is not working on it now.
I've forked it with minor change: https://github.com/ruschecker/CloudStorageMaven [I need in IAM auth]
If you want I can pick your changes and update package.

**Comment by gkatzioura** [comment]
Sorry I was not actively working on it.

**Pull request merged**
